name: ft_transcendence

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_container
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    restart: always
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - postgres



volumes:
  postgres_db:
    driver: local # Store data on the local machine (not remote storage like NFS or cloud)
    driver_opts: # driver options
      type: none # Don’t use any special filesystem type (like ext4, nfs, etc.)
      o: bind # Bind (attach) this volume to an existing directory on the host
      device: /home/mohamed-dahani/Desktop/projects/volumes/postgres_db # This is where data will physically be stored.
