/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "../app/**/*.{ts,tsx}",
    "../components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "var(--md-surface, #131313)",
        background: "var(--md-background, #131313)",
        "on-background": "var(--md-on-background, #e5e2e1)",
        "surface-bright": "var(--md-surface-bright, #393939)",
        "surface-dim": "var(--md-surface-dim, #131313)",
        "surface-container-lowest": "var(--md-surface-container-lowest, #0e0e0e)",
        "surface-container-low": "var(--md-surface-container-low, #1c1b1b)",
        "surface-container": "var(--md-surface-container, #201f1f)",
        "surface-container-high": "var(--md-surface-container-high, #2a2a2a)",
        "surface-container-highest": "var(--md-surface-container-highest, #353534)",
        "surface-variant": "var(--md-surface-variant, #353534)",
        "surface-tint": "var(--md-surface-tint, #c0c1ff)",
        "inverse-surface": "var(--md-inverse-surface, #e5e2e1)",
        "inverse-on-surface": "var(--md-inverse-on-surface, #313030)",
        primary: "var(--md-primary, #c0c1ff)",
        "on-primary": "var(--md-on-primary, #1000a9)",
        "primary-container": "var(--md-primary-container, #8083ff)",
        "on-primary-container": "var(--md-on-primary-container, #0d0096)",
        "primary-fixed": "var(--md-primary-fixed, #e1e0ff)",
        "primary-fixed-dim": "var(--md-primary-fixed-dim, #c0c1ff)",
        "on-primary-fixed": "var(--md-on-primary-fixed, #07006c)",
        "on-primary-fixed-variant": "var(--md-on-primary-fixed-variant, #2f2ebe)",
        "inverse-primary": "var(--md-inverse-primary, #494bd6)",
        secondary: "var(--md-secondary, #c8c6c5)",
        "on-secondary": "var(--md-on-secondary, #303030)",
        "secondary-container": "var(--md-secondary-container, #474746)",
        "on-secondary-container": "var(--md-on-secondary-container, #b7b5b4)",
        "secondary-fixed": "var(--md-secondary-fixed, #e5e2e1)",
        "secondary-fixed-dim": "var(--md-secondary-fixed-dim, #c8c6c5)",
        "on-secondary-fixed": "var(--md-on-secondary-fixed, #1b1b1c)",
        "on-secondary-fixed-variant": "var(--md-on-secondary-fixed-variant, #474746)",
        tertiary: "var(--md-tertiary, #ffb783)",
        "on-tertiary": "var(--md-on-tertiary, #4f2500)",
        "tertiary-container": "var(--md-tertiary-container, #d97721)",
        "on-tertiary-container": "var(--md-on-tertiary-container, #452000)",
        "tertiary-fixed": "var(--md-tertiary-fixed, #ffdcc5)",
        "tertiary-fixed-dim": "var(--md-tertiary-fixed-dim, #ffb783)",
        "on-tertiary-fixed": "var(--md-on-tertiary-fixed, #301400)",
        "on-tertiary-fixed-variant": "var(--md-on-tertiary-fixed-variant, #703700)",
        error: "var(--md-error, #ffb4ab)",
        "on-error": "var(--md-on-error, #690005)",
        "error-container": "var(--md-error-container, #93000a)",
        "on-error-container": "var(--md-on-error-container, #ffdad6)",
        outline: "var(--md-outline, #908fa0)",
        "outline-variant": "var(--md-outline-variant, #464554)",
        "on-surface": "var(--md-on-surface, #e5e2e1)",
        "on-surface-variant": "var(--md-on-surface-variant, #c7c4d7)",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "row-height-md": "40px",
        unit: "4px",
        "element-gap": "8px",
        "container-padding": "16px",
        "layout-margin": "24px",
        "row-height-sm": "32px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"],
        "headline-sm": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};