/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "../app/**/*.{ts,tsx}",
    "../components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#313030",
        "surface-bright": "#393939",
        "surface-container": "#201f1f",
        "tertiary-fixed": "#ffdcc5",
        "on-secondary-container": "#b7b5b4",
        "on-error": "#690005",
        surface: "#131313",
        primary: "#c0c1ff",
        "on-surface": "#e5e2e1",
        "inverse-primary": "#494bd6",
        secondary: "#c8c6c5",
        "primary-fixed": "#e1e0ff",
        "surface-variant": "#353534",
        "secondary-container": "#474746",
        "secondary-fixed-dim": "#c8c6c5",
        "inverse-surface": "#e5e2e1",
        "surface-tint": "#c0c1ff",
        "on-secondary-fixed": "#1b1b1c",
        "surface-container-low": "#1c1b1b",
        "error-container": "#93000a",
        "surface-container-highest": "#353534",
        "on-tertiary-container": "#452000",
        background: "#131313",
        "tertiary-fixed-dim": "#ffb783",
        "on-tertiary": "#4f2500",
        "surface-container-high": "#2a2a2a",
        "primary-fixed-dim": "#c0c1ff",
        "on-primary-fixed-variant": "#2f2ebe",
        "secondary-fixed": "#e5e2e1",
        "on-secondary-fixed-variant": "#474746",
        "on-background": "#e5e2e1",
        "surface-container-lowest": "#0e0e0e",
        "on-primary-container": "#0d0096",
        outline: "#908fa0",
        "on-secondary": "#303030",
        "on-tertiary-fixed": "#301400",
        "on-error-container": "#ffdad6",
        error: "#ffb4ab",
        "on-primary": "#1000a9",
        "tertiary-container": "#d97721",
        "outline-variant": "#464554",
        tertiary: "#ffb783",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#703700",
        "primary-container": "#8083ff",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed": "#07006c",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "row-height-md": "40px",
        unit: "4px",
        "element-gap": "8px",
        "container-padding": "16px",
        "layout-margin": "24px",
        "row-height-sm": "32px",
      },
      fontFamily: {
        "body-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Sora", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "mono-data": ["Inter", "sans-serif"],
        "headline-sm": ["Sora", "sans-serif"],
        "headline-md": ["Sora", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "mono-data": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-sm": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};