# -----------------------------------------------------------------------------
# HTTPS server — SSL/TLS termination + reverse proxy configuration
# -----------------------------------------------------------------------------

server {
	listen 443 ssl;
	listen [::]:443 ssl;
	server_name 127.0.0.1;

	# SSL certificates
	ssl_certificate      /etc/nginx/ssl/self-signed.crt;
	ssl_certificate_key  /etc/nginx/ssl/self-signed.key;

	# TLS Hardening
	ssl_protocols TLSv1.2 TLSv1.3;

	# Proxy settings
	proxy_set_header Host              $host;
	proxy_set_header X-Real-IP         $remote_addr;
	proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
	proxy_set_header X-Forwarded-Proto $scheme;

	proxy_connect_timeout 60s;
	proxy_send_timeout    60s;
	proxy_read_timeout    60s;

	# Routes
	location / {
		proxy_pass http://backend:3000/;
	}

	# Block access to hidden files
	location ~ /\. {
		deny all;
		return 404;
	}

	# Error pages
    error_page 502 503 504 /50x.json;
    location = /50x.json {
        internal;
        default_type application/json;
        return 502 '{"statusCode":502,"message":"Backend is temporarily unavailable."}';
    }

}